title: Learn Java for Beginners
description: 8 Week Backend Mentorship Program

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

url: "https://learn-java-for-beginners.github.io"
baseurl: ""

color_scheme: light
search_enabled: true
heading_anchors: true
back_to_top: true

aux_links:
  "View on GitHub":
    - "//github.com/learn-java-for-beginners/learn-java-for-beginners.github.io"

# Hide files from navigation
exclude:
  - LICENSE
  - README.md
  - mentor-notes/
